### ISSUE TITLE
[공통] App bar 제작

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#10]
## 설명

> 좌측: 우아한 가계부라는 타이틀
> 중앙: 현재 선택되어있는 월을 표시하고, 좌 우측 버튼을 통해 월을 한달씩 이동이 가능합니다. 
> 이동 후에는 section 에 보여줘야할 데이터를 바꿔줘야 합니다.
> 우측: 네이게이터에는 3개의 버튼이 있고, 좌측부터 메인, 달력, 통계 순으로 있습니다.
>  각 버튼 클릭시, section 에 보여질 화면이 달라집니다. 선택되어 있는 버튼은 하얀색, 아니면 회색

## 작업 내용

- [x] UI 제작
- [x] 월을 바꿀때마다 API 요청을 통해 해당월의 정보를 가져오기 ( 클라이언트, 서버 )

**Comment by qudgus21** [comment]
작업 예상시간 2h

**Comment by qudgus21** [comment]
작업완료 시간 - 6h+
