### ISSUE TITLE
[메인] 컨텍스트 메뉴 커스텀화

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#17]
## 설명

> 리스트를 우클릭 시, 수정하기 및 삭제하기가 있는 컨텍스트 메뉴를 제작합니다.

## 작업 내용

- [ ] 컨텍스트 메뉴를 수정
- [ ] 내역 수정 API 제작
- [x] 내역 삭제 API 제작
- [ ] 수정 시 해당 리스트를 input 태그로 변경
- [x] 삭제시 snack bar 사용
- [x] 수정 및 삭제 시, response 에 따라 state 값만 변경 ( API 재호출 x )

**Comment by 0woodev** [comment]
우클릭에 대해서 현재 고민중에 있습니다.

**Comment by qudgus21** [comment]
해당 기능 논의 후 구현하지 않기로 결정했습니다.
