### ISSUE TITLE
[달력] 총 수입, 지출, 합계 표시 기능

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#19]
## 설명

> 해당하는 년, 월의 총 합계, 지출, 수입을 표시합니다.

## 작업 내용

- [x] 해당 월의 총 합계, 지출, 수입 표시
- [x] 색상 : 회색
- [x] 위치 : 달력 하단

**Comment by qudgus21** [comment]
작업 시간 - 2h
