### ISSUE TITLE
[통계] 카테고리별 지출 변화 추이 그래프 기능

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#21]
## 설명

> 각 카테고리를 클릭시, 해당 년도의 특정 카테고리 1월부터 12월까지의 지출 추이를 그래프로 보여줍> 니다. 또한, 조건에 맞는 지출 상세 내역을 모두 보여줍니다. ( 년, 월, 카테고리 )

## 작업 내용

- [x]  꺾은선 그래프 제작
- [x] 해당 년도의 1월부터 12월까지의 변화 추이를 가져오는 API ( 클라이언트, 서버 )
- [x] 해당 년, 월과 카테고리에 해당하는 지출 내역을 전부 가져오는 API ( 클라이언트, 서버 )
- [x] 지출 내역의 UI 는 메인화면의 리스트와 동일

**Comment by qudgus21** [comment]
작업시간 - 12h +
