### ISSUE TITLE
백엔드 구조 잡기

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#5]
## 설명

> express 서버와 DB 구조를 잡아야 합니다.

## 작업 내용

- [x] 파일 구조 ( router, service )
- [x] ERD
- [x] cors
- [x] sequelize 설정
- [x] jwt 설정
- [x] ERD 를 기반으로 sequelize 모델 제작

**Comment by qudgus21** [comment]
예상 작업 시간 : 2h

**Comment by 0woodev** [comment]
페어프로그래밍을 통해 진행했습니다.

실제 작업 소요시간 : 4h

작업하면서, 겪었던 trouble shooting
1. module.exports = function (req, res) { ... }  이거를  const { decodeJWT } = require('...') 이렇게 해서 안됐던것.
2. createdAt, updatedAt default value 를 sequelize 를 통해 설정하는 방법

**Comment by 0woodev** [comment]
남은 작업 
1. timezone 설정
2. 나머지 테이블 모델 구현

**Comment by qudgus21** [comment]
작업소요시간 : 1h

작업내용
- timezone 설정
- 나머지 테이블 모델 구현
- 필요한 파일 생성
