### ISSUE TITLE
[공통] 회원가입 기능

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#6]
## 설명

> 유저가 회원가입 할 수 있도록 프론트 부터 백엔드까지 작업합니다.

## 작업 내용

- [x] 플로팅 액션 버튼
- [x] 회원가입 모달 띄우기
- [x] API 클라이너트
- [x] API 서버
- [x] POSTMAN 혹은 클라이언트를 통한 테스트

**Comment by qudgus21** [comment]
작업 예상 소요시간 2-3h

**Comment by 0woodev** [comment]
남은 작업
- 플로팅 버튼
- 모달 띄우기

**Comment by 0woodev** [comment]
예상 소요 작업 시간
- 2~3 h

**Comment by 0woodev** [comment]
실제 작업시간 : 3시간 반
