### ISSUE TITLE
깃헙 자동배포 및 웹팩 설정

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#60]
## 설명

> 깃헙 자동배포와 웹팩 빌드시 이미지를 불러오지 못하는 버그 픽스, 경로 alias 설정 등을 해야합니다.

## 작업 내용

- [ ] 깃헙 자동배포
- [x] 웹팩 빌드시 이미지를 불러오지 못하는 버그 픽스
- [x] 경로 alias 설정
- [ ] DNS 적용까지 (옵션)

**Comment by qudgus21** [comment]
이미지 불러오지 못하는 버그는 s3로 대체
