### ISSUE TITLE
메인페이지 남은 기능

### ISSUE THREAD

**Issue by 0woodev** [woowa-techcamp-2021/cashbook-11#61]
## 설명

> 간단하게 남은 기능들을 구현해봅시다.

## 작업 내용

- [x] 로그인 전에는 플로팅 버튼에서 로그인 버튼이 계속 통통 튀도록 설정합니다.
- [ ] 소리를 넣었으면 합니다. ( 추가, 삭제 등등 ) (옵션)
- [x] 검색 기능 버그 픽스
- [x] 검색바 안에 내용물이 많아서 아래로 펼치기 접기 버튼이 있으면 좋을 것 같습니다.

**Comment by 0woodev** [comment]
날짜로 인한 검색기능 버그 픽스했습니다.

**Comment by qudgus21** [comment]
소리는 고민중입니다.
